version: '3'
services:
    selenium:
        image: selenium/standalone-firefox:106.0
        build:
          context:
              shm_size: '2gb'
        shm_size: '2gb'
        container_name: firefox
        restart: always
        volumes:
        - ./:/app
        ports:
          - 4444:4444
          - 7900:7900